import { MongoDataType } from '../types';

export const mongoDataTypesList: MongoDataType[] = [
  {
    name: "String",
    codeSnippet: `"product_name": "TV"`,
    description: "The most commonly used datatype to store textual information. All strings stored in MongoDB must be valid UTF-8.",
    sampleValue: `"product_code": "1234-ABCD"`
  },
  {
    name: "Integer",
    codeSnippet: `"stock_quantity": 42`,
    description: "Stores numerical values without decimal places. Can be 32-bit (NumberInt) or 64-bit (NumberLong) depending on server architecture and value scale.",
    sampleValue: `NumberInt(42) or 100`
  },
  {
    name: "Double",
    codeSnippet: `"product_price": 49999.99`,
    description: "Numeric numbers containing 8-byte IEEE 754 floating-point precision, ideal for pricing and scientific calculations.",
    sampleValue: `49999.99`
  },
  {
    name: "Boolean",
    codeSnippet: `"product_availability": true`,
    description: "Stores logical binary flag values: either true or false.",
    sampleValue: `true / false`
  },
  {
    name: "Array",
    codeSnippet: `"product_feature": ["HD", "10wt"]`,
    description: "Stores a list or set of multiple values (homogeneous or heterogeneous) inside a single key of the document.",
    sampleValue: `["HD", "10wt", "SmartTV"]`
  },
  {
    name: "Object (Embedded Document)",
    codeSnippet: `"product_dimensions": { "product_height": 55, "product_width": 75 }`,
    description: "An embedded document containing key-value pairs stored inside another document, enabling rich hierarchical modeling.",
    sampleValue: `{ "height": 55, "width": 75 }`
  },
  {
    name: "Date",
    codeSnippet: `"mfd_date": ISODate("2022-04-10T12:45:42")`,
    description: "Stores the date and time in 64-bit integer format (milliseconds since UNIX epoch). Three strategies exist: Date() returns a string; new Date() returns a Date object; ISODate() returns a BSON Date object.",
    sampleValue: `ISODate("2022-04-10T12:45:42Z")`
  },
  {
    name: "Timestamp",
    codeSnippet: `"product_created": Timestamp(1531456567, 1)`,
    description: "A 64-bit value used internally by MongoDB to record the precise date and time of an occurrence (first 32 bits for timestamp, next 32 bits for increment ordinal). Commonly used to track oplog operations, creation, and updates.",
    sampleValue: `Timestamp(1531456567, 1)`
  },
  {
    name: "Null",
    codeSnippet: `"discount_coupon": null`,
    description: "Used to represent a value of zero, empty, or non-existent value in a field.",
    sampleValue: `null`
  },
  {
    name: "Binary Data (BinData)",
    codeSnippet: `"product_picture": BinData(1, "rk56tyvbu5677ghugf456.")`,
    description: "Used to store raw binary byte streams such as images, cryptographic keys, or encoded files directly within the document.",
    sampleValue: `BinData(1, "rk56tyvbu5677ghugf456.")`
  },
  {
    name: "ObjectId",
    codeSnippet: `"_id": ObjectId("64f1a2b3c4d5e6f7a8b9c0d1")`,
    description: "A small, 12-byte unique BSON value generated by default for the mandatory _id primary key field.",
    sampleValue: `ObjectId("...")`
  },
  {
    name: "Min / Max Keys",
    codeSnippet: `"bound": MinKey`,
    description: "Special internal sentinel types used primarily in indexing and sharding to compare a value against the lowest (MinKey) or highest (MaxKey) possible BSON elements.",
    sampleValue: `MinKey / MaxKey`
  }
];

export const completeDocumentExample = `{
  "_id": "1",
  "product_code": "1234-ABCD",
  "product_name": "TV",
  "product_price": 49999.99,
  "product_feature": ["HD", "10wt"],
  "product_dimensions": {
    "product_height": 55,
    "product_width": 75
  },
  "mfd_date": ISODate("2022-04-10T12:45:42"),
  "product_created": Timestamp(1531456567, 1),
  "product_availability": true,
  "product_picture": BinData(1, "rk56tyvbu5677ghugf456.")
}`;
